In [1]:
import torch
from torch.nn import Conv1d

In [2]:
batch_size = 2
one_hot_size = 10
sequence_width = 7
data = torch.randn(batch_size, one_hot_size, sequence_width)

In [3]:
data.shape

torch.Size([2, 10, 7])

In [4]:
data

tensor([[[-0.6219, -0.1680,  1.3520,  0.3210, -1.4402, -0.5448, -0.8081],
         [ 0.7121,  0.4321, -0.2606,  1.1901,  0.2798,  0.4465,  2.1183],
         [ 0.7935, -0.1387, -0.1899,  0.3731, -0.2763, -0.1163,  1.5625],
         [-0.5841, -0.4324, -0.8295, -0.3808, -0.0302,  1.2179, -1.0522],
         [-0.7925,  0.3804,  0.2446,  2.1622,  0.7783,  2.2627, -0.6631],
         [-1.4528,  0.9285, -1.0422,  0.5922, -1.9192,  1.5527,  0.8156],
         [-0.0464,  0.7881,  0.6417,  1.1330, -0.4511, -0.4321,  1.2084],
         [-0.1564, -0.4364, -0.6472, -0.2623,  0.3000, -1.2736, -0.8436],
         [ 0.5017,  0.3790, -0.1732,  1.6913, -0.4878,  1.2528,  1.1652],
         [-0.0694, -0.6995,  0.1881,  0.8920, -0.0536,  1.5153, -0.2200]],

        [[-0.2425,  1.2650, -0.0366, -0.0559, -2.4526,  0.0638, -0.8232],
         [-0.5606,  0.2451,  0.8077,  1.4782,  0.7036,  0.2706,  1.9432],
         [ 1.0945,  1.2127, -1.0351, -1.2778,  0.5462,  0.2006,  0.7234],
         [ 1.3202, -0.8970,  0.8892,

In [5]:
conv1 = Conv1d(in_channels=one_hot_size, out_channels=16,
               kernel_size=3, bias=False)
intermediate1 = conv1(data)

In [6]:
intermediate1.shape

torch.Size([2, 16, 5])

In [7]:
intermediate1

tensor([[[ 0.0901,  0.0003, -0.3199, -0.9161,  0.8891],
         [ 0.4652, -0.4227,  0.4440,  0.5596,  0.9235],
         [ 0.2727, -0.1083, -0.2478, -0.2539,  0.4428],
         [-0.2479, -0.0118, -0.5224, -0.0155,  0.2024],
         [ 0.2169,  0.4973,  0.6512,  0.2573, -0.0274],
         [ 0.2911,  0.5659, -0.1995, -0.4643, -0.4578],
         [-0.0002, -0.6867,  0.3004,  0.4629,  0.3116],
         [-0.3022,  0.1271,  0.1603,  0.0945,  0.2474],
         [-0.3859, -0.8344, -0.8762, -0.5775, -0.4378],
         [-0.3991, -0.6021, -0.1934,  0.3160, -0.9253],
         [-0.1730, -0.0039, -0.0610,  0.2906,  1.6090],
         [-0.7163, -0.3277, -1.0414, -0.0690, -0.3708],
         [ 0.3715,  0.1505,  0.1153,  0.2613, -0.8192],
         [-0.0618,  0.0977,  0.6547, -0.4010,  1.3571],
         [-0.1815,  0.0697,  0.5494,  0.9440,  0.4698],
         [ 0.5741, -0.2263,  0.8628,  0.0861,  0.2144]],

        [[ 0.0029, -0.0392, -0.0281, -1.0474,  0.7267],
         [-0.2415,  0.6609,  0.1238,  0.5088, 

In [8]:
channels00 = data[0,:,:3]
channels00

tensor([[-0.6219, -0.1680,  1.3520],
        [ 0.7121,  0.4321, -0.2606],
        [ 0.7935, -0.1387, -0.1899],
        [-0.5841, -0.4324, -0.8295],
        [-0.7925,  0.3804,  0.2446],
        [-1.4528,  0.9285, -1.0422],
        [-0.0464,  0.7881,  0.6417],
        [-0.1564, -0.4364, -0.6472],
        [ 0.5017,  0.3790, -0.1732],
        [-0.0694, -0.6995,  0.1881]])

In [9]:
k00 = conv1.weight[0]
k00

tensor([[-0.0721, -0.0002,  0.1296],
        [-0.0677, -0.1056,  0.0488],
        [ 0.1373, -0.1272,  0.1493],
        [ 0.1533, -0.0636,  0.0785],
        [ 0.0214, -0.0323, -0.0598],
        [-0.0063,  0.1599, -0.0418],
        [-0.0976, -0.0314,  0.0052],
        [ 0.0980, -0.0927,  0.1446],
        [-0.0599,  0.1381,  0.0849],
        [-0.1266,  0.1480,  0.1100]], grad_fn=<SelectBackward>)

In [10]:
channels00 * k00

tensor([[ 0.0449,  0.0000,  0.1752],
        [-0.0482, -0.0456, -0.0127],
        [ 0.1089,  0.0176, -0.0284],
        [-0.0895,  0.0275, -0.0651],
        [-0.0169, -0.0123, -0.0146],
        [ 0.0092,  0.1485,  0.0435],
        [ 0.0045, -0.0248,  0.0033],
        [-0.0153,  0.0405, -0.0936],
        [-0.0300,  0.0523, -0.0147],
        [ 0.0088, -0.1035,  0.0207]], grad_fn=<ThMulBackward>)

In [11]:
torch.sum(channels00 * k00)

tensor(0.0901, grad_fn=<SumBackward0>)

In [12]:
channels12 = data[1,:,2:5]
channels12

tensor([[-0.0366, -0.0559, -2.4526],
        [ 0.8077,  1.4782,  0.7036],
        [-1.0351, -1.2778,  0.5462],
        [ 0.8892,  0.4730, -0.7384],
        [ 0.1836, -0.4377,  0.5701],
        [-0.4346,  1.3623, -2.5753],
        [-1.8953, -0.0718,  0.9929],
        [ 0.0435, -0.0359,  0.4721],
        [ 0.1007,  0.1343, -0.4479],
        [ 0.7102, -0.7086, -0.4247]])

In [13]:
k13 = conv1.weight[13]
k13

tensor([[ 0.1624, -0.1039, -0.1720],
        [-0.1783,  0.0096,  0.1440],
        [-0.0998, -0.1750,  0.1277],
        [ 0.1133, -0.0456, -0.0951],
        [ 0.0632, -0.0484,  0.1090],
        [-0.1539,  0.0436, -0.0296],
        [-0.1054,  0.0910,  0.1060],
        [ 0.1817, -0.1722,  0.0242],
        [-0.1057,  0.1532,  0.1536],
        [ 0.1221, -0.1309, -0.1538]], grad_fn=<SelectBackward>)

In [14]:
torch.sum(data[1,:,2:5] * conv1.weight[13])

tensor(1.7465, grad_fn=<SumBackward0>)

In [15]:
intermediate1[1, 13, 2]

tensor(1.7465, grad_fn=<SelectBackward>)

In [17]:
conv2 = torch.nn.Conv1d(in_channels=16, out_channels=16, kernel_size=3, bias=False)

In [18]:
intermediate2 = conv2(intermediate1)

In [19]:
intermediate2.shape

torch.Size([2, 16, 3])

In [20]:
intermediate3 = conv2(intermediate2)

In [21]:
intermediate3.shape

torch.Size([2, 16, 1])

In [22]:
intermediate3

tensor([[[ 0.6801],
         [-0.0658],
         [ 0.0850],
         [ 0.2171],
         [ 0.1138],
         [-0.0139],
         [ 0.1066],
         [ 0.0904],
         [ 0.0464],
         [ 0.1474],
         [-0.0591],
         [ 0.2361],
         [ 0.1979],
         [ 0.1827],
         [-0.0146],
         [-0.0222]],

        [[ 0.4419],
         [-0.0139],
         [-0.0295],
         [ 0.1822],
         [ 0.1237],
         [-0.0139],
         [-0.0829],
         [-0.1684],
         [-0.1315],
         [-0.1350],
         [ 0.0277],
         [ 0.2410],
         [-0.0098],
         [ 0.1045],
         [ 0.0241],
         [ 0.0154]]], grad_fn=<SqueezeBackward1>)

In [23]:
conv2.weight.shape

torch.Size([16, 16, 3])

In [27]:
torch.squeeze(intermediate3)

tensor([[ 0.6801, -0.0658,  0.0850,  0.2171,  0.1138, -0.0139,  0.1066,  0.0904,
          0.0464,  0.1474, -0.0591,  0.2361,  0.1979,  0.1827, -0.0146, -0.0222],
        [ 0.4419, -0.0139, -0.0295,  0.1822,  0.1237, -0.0139, -0.0829, -0.1684,
         -0.1315, -0.1350,  0.0277,  0.2410, -0.0098,  0.1045,  0.0241,  0.0154]],
       grad_fn=<SqueezeBackward0>)

In [47]:
intermediate2

tensor([[[ 0.2627, -0.3585, -0.5961],
         [-0.1940, -0.0053, -0.1540],
         [ 0.4711,  0.1474, -0.1635],
         [-0.2695, -0.2335, -0.6915],
         [ 0.2591, -0.1467,  0.7620],
         [ 0.5435,  0.2187,  0.2751],
         [ 0.6720,  0.0429, -0.3341],
         [-0.5277, -0.5049, -1.0008],
         [-0.3224,  0.2023, -0.0865],
         [-0.0740, -0.1020, -0.0905],
         [-0.0571, -0.0774, -0.2565],
         [ 0.1281,  0.0578,  0.4288],
         [-0.2005,  0.0749, -0.3955],
         [ 0.2699,  0.0364,  0.4295],
         [-0.0431,  0.1029, -0.7587],
         [ 0.0445,  0.2067, -0.2388]],

        [[-0.3228, -0.3062, -0.4556],
         [-0.2603,  0.0021,  0.3486],
         [ 0.1633, -0.2749,  0.0454],
         [ 0.0768, -0.1083, -0.2975],
         [-0.1386, -0.1375,  0.5079],
         [ 0.3940, -0.3681, -0.0819],
         [ 0.5651,  0.0163, -0.2528],
         [-0.3852, -0.1315, -0.4178],
         [ 0.2998,  0.2365, -0.0244],
         [ 0.2037, -0.2136, -0.3032],
         [

In [48]:
intermediate2.flatten(start_dim=1)

tensor([[ 0.2627, -0.3585, -0.5961, -0.1940, -0.0053, -0.1540,  0.4711,  0.1474,
         -0.1635, -0.2695, -0.2335, -0.6915,  0.2591, -0.1467,  0.7620,  0.5435,
          0.2187,  0.2751,  0.6720,  0.0429, -0.3341, -0.5277, -0.5049, -1.0008,
         -0.3224,  0.2023, -0.0865, -0.0740, -0.1020, -0.0905, -0.0571, -0.0774,
         -0.2565,  0.1281,  0.0578,  0.4288, -0.2005,  0.0749, -0.3955,  0.2699,
          0.0364,  0.4295, -0.0431,  0.1029, -0.7587,  0.0445,  0.2067, -0.2388],
        [-0.3228, -0.3062, -0.4556, -0.2603,  0.0021,  0.3486,  0.1633, -0.2749,
          0.0454,  0.0768, -0.1083, -0.2975, -0.1386, -0.1375,  0.5079,  0.3940,
         -0.3681, -0.0819,  0.5651,  0.0163, -0.2528, -0.3852, -0.1315, -0.4178,
          0.2998,  0.2365, -0.0244,  0.2037, -0.2136, -0.3032,  0.1621,  0.1139,
          0.0331, -0.5001, -0.2128,  0.0686, -0.2775, -0.2258, -0.2112, -0.0323,
         -0.5423,  0.4796,  0.3939, -0.0768,  0.0455,  0.5688,  0.2298, -0.4378]],
       grad_fn=<AsStrided

In [50]:
intermediate2.view(2, -1)

tensor([[ 0.2627, -0.3585, -0.5961, -0.1940, -0.0053, -0.1540,  0.4711,  0.1474,
         -0.1635, -0.2695, -0.2335, -0.6915,  0.2591, -0.1467,  0.7620,  0.5435,
          0.2187,  0.2751,  0.6720,  0.0429, -0.3341, -0.5277, -0.5049, -1.0008,
         -0.3224,  0.2023, -0.0865, -0.0740, -0.1020, -0.0905, -0.0571, -0.0774,
         -0.2565,  0.1281,  0.0578,  0.4288, -0.2005,  0.0749, -0.3955,  0.2699,
          0.0364,  0.4295, -0.0431,  0.1029, -0.7587,  0.0445,  0.2067, -0.2388],
        [-0.3228, -0.3062, -0.4556, -0.2603,  0.0021,  0.3486,  0.1633, -0.2749,
          0.0454,  0.0768, -0.1083, -0.2975, -0.1386, -0.1375,  0.5079,  0.3940,
         -0.3681, -0.0819,  0.5651,  0.0163, -0.2528, -0.3852, -0.1315, -0.4178,
          0.2998,  0.2365, -0.0244,  0.2037, -0.2136, -0.3032,  0.1621,  0.1139,
          0.0331, -0.5001, -0.2128,  0.0686, -0.2775, -0.2258, -0.2112, -0.0323,
         -0.5423,  0.4796,  0.3939, -0.0768,  0.0455,  0.5688,  0.2298, -0.4378]],
       grad_fn=<ViewBackw

In [51]:
intermediate2.mean(dim=2)

tensor([[-0.2307, -0.1178,  0.1517, -0.3982,  0.2915,  0.3458,  0.1269, -0.6778,
         -0.0689, -0.0888, -0.1303,  0.2049, -0.1737,  0.2453, -0.2330,  0.0041],
        [-0.3616,  0.0301, -0.0221, -0.1097,  0.0773, -0.0187,  0.1095, -0.3115,
          0.1706, -0.1044,  0.1030, -0.2148, -0.2382, -0.0316,  0.1209,  0.1203]],
       grad_fn=<MeanBackward0>)

In [52]:
intermediate2[:,:,0]

tensor([[ 0.2627, -0.1940,  0.4711, -0.2695,  0.2591,  0.5435,  0.6720, -0.5277,
         -0.3224, -0.0740, -0.0571,  0.1281, -0.2005,  0.2699, -0.0431,  0.0445],
        [-0.3228, -0.2603,  0.1633,  0.0768, -0.1386,  0.3940,  0.5651, -0.3852,
          0.2998,  0.2037,  0.1621, -0.5001, -0.2775, -0.0323,  0.3939,  0.5688]],
       grad_fn=<SelectBackward>)